// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const dotenv = require("dotenv").config({
	quiet: true,
	debug: false,
});

const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: process.env["DIRECT_URL"],
		// url: process.env["DATABASE_URL"],
	},
});
